from .event_admin import EventAdmin
from .contact_admin import ContactAdmin
from .contract_admin import ContractAdmin
from ...frontend.admin.custom_admin_site import  CustomAdminSite
from .erc20_balances import  erc20_balances_view
from .avax_balances import  avax_balances_view
from .fizit_balances import  fizit_balances_view
from .view_contract import  view_contract_view
from .list_contracts import  list_contracts_view