from rest_framework import serializers

class SettlementSerializer(serializers.Serializer):
    contract_idx = serializers.IntegerField(read_only=True)
    settle_idx = serializers.IntegerField(read_only=True)
    contract_name = serializers.CharField(read_only=True, max_length=50)
    extended_data = serializers.JSONField()
    funding_instr = serializers.CharField(read_only=True)
    deposit_instr = serializers.CharField(read_only=True)
    settle_due_dt = serializers.DateTimeField() 
    transact_min_dt =  serializers.DateTimeField()  
    transact_max_dt =  serializers.DateTimeField() 
    transact_count = serializers.IntegerField(read_only=True)
    advance_amt = serializers.CharField(max_length=20, default = "0.00")
    advance_amt_gross = serializers.CharField(max_length=20, default = "0.00")
    settle_pay_dt =  serializers.DateTimeField(read_only=True) 
    settle_exp_amt = serializers.CharField(max_length=20, default = "0.00")
    settle_pay_amt = serializers.CharField(max_length=20, default = "0.00")
    dispute_amt = serializers.CharField(max_length=20, default = "0.00")
    dispute_reason =  serializers.CharField(read_only=True,max_length=1000)
    days_late = serializers.IntegerField(read_only=True)
    late_fee_amt = serializers.CharField(max_length=20, default = "0.00")
    residual_pay_dt =  serializers.DateTimeField(read_only=True)  
    residual_exp_amt = serializers.CharField(max_length=20, default = "0.00")
    residual_pay_amt = serializers.CharField(max_length=20, default = "0.00")
    residual_calc_amt = serializers.CharField(max_length=20, default = "0.00")